services:
  - type: web
    name: cal-web
    plan: standard
    repo: https://github.com/calcom/docker-render.git
    env: docker
    envVars:

      - key: DATABASE_URL
        fromDatabase:
          name: cal-postgres
          property: connectionString

      - key: NEXT_PUBLIC_WEBAPP_URL
        value: https://cal-web.onrender.com

      - key: CALENDSO_ENCRYPTION_KEY
        value: secret

      - key: NEXTAUTH_URL
        value: https://cal-web.onrender.com

      - key: NEXTAUTH_SECRET
        value: secret

      - key: CRON_API_KEY
        value: 0cc0e6c35519bba620c9360cfe3e68d0

databases:
  - name: cal-postgres
    plan: starter
